services:

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    command: mongod --bind_ip_all --replSet rs0
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017',priority:1},{_id:1,host:'mongo-secondary:27017',priority:0.5}]}) }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    container_name: lila_mongo
    networks:
      lila-network:
        aliases:
          - mongo.localhost
        ipv4_address: 172.22.0.2
    ports:
      - 27017:27017
    profiles:
      - all
      - infra
      - ws
      - stockfish-play
    volumes:
      # use `docker exec -it lila_mongo bash` to get a shell inside mongo
      # container. Directory containing this docker-compose.yml will be mounted
      # as /host inside container so you can import db dumps, etc.
      - .:/host
      - data-mongo:/data/db

  mongo-secondary:
    image: mongo:5.0
    container_name: lila_mongo_secondary
    command: mongod --bind_ip_all --replSet rs0
    networks:
      lila-network:
        aliases:
          - mongo-secondary.localhost
        ipv4_address: 172.22.0.3
    depends_on:
      - mongo
    ports:
      - 27018:27017
    profiles:
      - all
      - infra
      - ws
      - stockfish-play

  redis:
    image: redis:6-alpine
    container_name: lila_redis
    networks:
      lila-network:
        aliases:
          - redis.localhost
        ipv4_address: 172.22.0.5
    ports:
      - 6379:6379
    profiles:
      - all
      - infra
      - ws
      - stockfish-play

  influx:
    image: influxdb:2.7-alpine
    restart: unless-stopped
    container_name: lila_influx
    networks:
      lila-network:
        aliases:
          - influx.localhost
        ipv4_address: 172.22.0.6
    ports:
      - 8086:8086
    volumes:
      - data-influx:/var/lib/influxdb2
    profiles:
      - monitor

  prometheus:
    image: prom:/prometheus:v2.55.1
    volumes:
     - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      lila-network:
        aliases:
          - prometheus.localhost
    ports:
     - 9090:9090
    profiles:
      - monitor

  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: lila_elastic_search
    networks:
      lila-network:
        aliases:
          - elasticsearch.localhost
        ipv4_address: 172.22.0.7
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - http.cors.allow-origin=/.*/
      - http.cors.enabled=true
      - xpack.security.enabled=false
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    profiles:
      - all
      - infra
      - search

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: lila_kibana
    restart: unless-stopped
    ports:
      - 5601:5601
    networks:
      lila-network:
        aliases:
          - kibana.localhost
        ipv4_address: 172.22.0.8
    volumes:
      - ./conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    profiles:
      - all
      - search

  elasticvue:
    image: cars10/elasticvue:1.0.7
    container_name: lila_elasticvue
    restart: unless-stopped
    volumes:
      - ./conf/elasticvue.json:/usr/share/nginx/html/api/default_clusters.json
    ports:
      - 8092:8080
    networks:
      lila-network:
        aliases:
          - elasticvue.localhost
        ipv4_address: 172.22.0.9
    profiles:
      - all
      - search

  lila-ws:
    image: ghcr.io/lichess-org/lila-ws:latest
    platform: linux/amd64
    container_name: lila_ws
    networks:
      lila-network:
        aliases:
          - lila-ws.localhost
        ipv4_address: 172.22.0.10
    volumes:
      - ./logs/lila-ws-error.log:/opt/docker/logs/error.log
    environment:
      - CONFIG_FORCE_mongo_uri=mongodb://mongo:27017/lichess?appName=lila-ws
      - CONFIG_FORCE_redis.uri=redis://redis:6379
    ports:
      - 9664:9664
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    profiles:
      - all
      - ws
      - stockfish-play

  fishnet-play:
    image: niklasf/fishnet:2.9.2
    container_name: lila_fishnet_play
    restart: unless-stopped
    entrypoint: /fishnet --endpoint http://lila_fishnet:9665/fishnet --max-backoff 5
    networks:
      lila-network:
        aliases:
          - fishnet-play.localhost
        ipv4_address: 172.22.0.11
    profiles:
      - all
      - stockfish-play

  lila-fishnet:
    image: ghcr.io/lichess-org/lila-fishnet:3.0.11
    container_name: lila_fishnet
    volumes:
      - ./logs:/opt/docker/logs:rw
    environment:
      - APP_BACKUP_FILE=/backup.json
      - CONFIG_FORCE_kamon_influxdb_authentication_token=secret
      - CONFIG_FORCE_kamon_influxdb_hostname=influxdb
      - REDIS_HOST=redis
    restart: unless-stopped
    networks:
      lila-network:
        aliases:
          - lila-fishnet.localhost
        ipv4_address: 172.22.0.12
    profiles:
      - all
      - stockfish-play
    depends_on:
      - redis
      - mongo
      - lila-ws

volumes:
  data-mongo:
  data-influx:
  data-elasticsearch:
  conf:
  prometheus_data: {}
  logs:

networks:
  lila-network:
    name: lila-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.254

